const KEY='brunstreg-data-v1';
const defaultSettings={cycleDays:21,gestationDays:280,watchDays:2,notify:true,morningTime:'06:45'};
let state=load(); let route='today'; let installPrompt=null;

const SIGNS=[
  ['restless','Uro / auka aktivitet',1],['mounts','Hoppar på andre',2],['standing','Står for opphopping',5],
  ['mucus','Klårt slim',2],['vulva','Hoven eller raud vulva',1],['feed','Mindre fôropptak',1],['voice','Rautar meir',1],
  ['blood','Blod',0]
];
const SEMEN_TYPES=['Sperm vital','Normal','Redex','Angus'];
function load(){try{const stored=JSON.parse(localStorage.getItem(KEY)||'{}');return {...{cows:[],events:[],morningChecks:{},settings:defaultSettings},...stored,morningChecks:stored.morningChecks||{},settings:{...defaultSettings,...(stored.settings||{})}}}catch{return {cows:[],events:[],morningChecks:{},settings:defaultSettings}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const fmt=d=>new Intl.DateTimeFormat('nb-NO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d));
const fmtDate=d=>new Intl.DateTimeFormat('nb-NO',{dateStyle:'medium'}).format(new Date(d));
const hours=(a,b=Date.now())=>(b-new Date(a).getTime())/36e5;
const days=(a,b=Date.now())=>(b-new Date(a).getTime())/864e5;
function cowName(c){return c.name?`${c.name} · ${c.number}`:c.number}
function eventsFor(id,type){return state.events.filter(e=>e.cowId===id&&(!type||e.type===type)).sort((a,b)=>new Date(b.at)-new Date(a.at))}
function activePregnancy(c){const pregnant=eventsFor(c.id,'pregnant')[0],ended=eventsFor(c.id).find(e=>['notPregnant','calving'].includes(e.type));return pregnant&&(!ended||new Date(pregnant.at)>new Date(ended.at))?pregnant:null}
function latestCalving(c){const event=eventsFor(c.id,'calving')[0],profile=c.lastCalving?{at:c.lastCalving}:null;if(!event)return profile;if(!profile)return event;return new Date(event.at)>new Date(profile.at)?event:profile}
function heatAnchor(c){return [eventsFor(c.id,'observation')[0],eventsFor(c.id,'insemination')[0],latestCalving(c)].filter(Boolean).sort((a,b)=>new Date(b.at)-new Date(a.at))[0]||null}
function inseminationEligibleDate(c){const calving=latestCalving(c);if(!calving)return null;const date=new Date(calving.at);date.setDate(date.getDate()+42);return date}
function inseminationEligibilityText(c){const date=inseminationEligibleDate(c);if(!date)return '';const today=new Date();today.setHours(0,0,0,0);const eligibleDay=new Date(date);eligibleDay.setHours(0,0,0,0);return eligibleDay>=today?`Kan inseminerast frå ${fmtDate(date)}`:''}
function compareCowNumber(a,b){return String(a.number||'').localeCompare(String(b.number||''),'nb',{numeric:true,sensitivity:'base'})}
function compareExpectedHeat(a,b){const ad=rollingHeatDate(a.c),bd=rollingHeatDate(b.c);return (ad?ad.getTime():Number.MAX_SAFE_INTEGER)-(bd?bd.getTime():Number.MAX_SAFE_INTEGER)||compareCowNumber(a.c,b.c)}
function rollingHeatDate(c){if(activePregnancy(c))return null;const anchor=heatAnchor(c);if(!anchor)return null;const due=new Date(anchor.at);due.setDate(due.getDate()+Number(state.settings.cycleDays));const today=new Date();today.setHours(0,0,0,0);while(due<today)due.setDate(due.getDate()+Number(state.settings.cycleDays));return due}
function expectedCalving(c){const pregnant=activePregnancy(c);if(!pregnant)return null;if(pregnant.expectedCalving)return new Date(pregnant.expectedCalving);const insemination=eventsFor(c.id,'insemination').find(e=>new Date(e.at)<=new Date(pregnant.at));if(!insemination)return null;const due=new Date(insemination.at);due.setDate(due.getDate()+Number(state.settings.gestationDays));return due}
function status(c){
  const pregnant=activePregnancy(c);
  if(pregnant){const due=expectedCalving(c);return {level:'green',label:due?`Drektig · kalving ${fmtDate(due)}`:'Drektig',priority:0}}
  const recent=eventsFor(c.id,'observation').filter(e=>hours(e.at)<=24);
  const score=recent.reduce((n,e)=>n+(e.signs||[]).reduce((s,k)=>s+(SIGNS.find(x=>x[0]===k)?.[2]||0),0),0);
  const standing=recent.some(e=>e.signs?.includes('standing'));
  const inseminated=eventsFor(c.id,'insemination')[0];
  if(standing||score>=7)return {level:'red',label:'Kontakt inseminør',priority:4};
  if(score>=4)return {level:'orange',label:'Truleg brunst',priority:3};
  if(score>=2)return {level:'yellow',label:'Følg nøye med',priority:2};
  const due=rollingHeatDate(c);
  if(due){const today=new Date();today.setHours(0,0,0,0);const until=Math.round((due-today)/864e5);if(until<=state.settings.watchDays)return {level:'yellow',label:until>0?`Venta brunst om ${until} d`:'Venta brunst i dag',priority:2}}
  if(inseminated)return {level:'green',label:'Inseminert · syklus følgd',priority:0};
  return {level:'green',label:'Ingen varsel',priority:0};
}
function nextHeat(c){if(activePregnancy(c))return 'Stoppa – kua er drektig';const due=rollingHeatDate(c);return due?fmtDate(due):'Ikkje berekna'}
function windowText(c){const e=eventsFor(c.id,'observation').find(x=>x.signs?.includes('standing'));if(!e)return '';const from=new Date(new Date(e.at).getTime()+8*36e5),to=new Date(new Date(e.at).getTime()+16*36e5);return `Rettleiande vindauge: ${fmt(from)}–${to.toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'})}`}
function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===route));({today:renderToday,cows:renderCows,observe:renderObserve,history:renderHistory,settings:renderSettings}[route]||renderToday)()}
function renderToday(){
  const list=state.cows.map(c=>({c,s:status(c)})).sort(compareExpectedHeat);
  const watch=list.filter(x=>x.s.priority>0);
  $('#app').innerHTML=`<section class="hero"><h1>God ${new Date().getHours()<12?'morgon':new Date().getHours()<18?'dag':'kveld'}!</h1><p>Her er status i besetninga akkurat no.</p><div class="summary"><div><strong>${state.cows.length}</strong>kyr</div><div><strong>${watch.length}</strong>å følgje</div><div><strong>${list.filter(x=>x.s.level==='red').length}</strong>klare varsel</div></div></section>${morningOverview(watch)}<h2>Kyr å følgje i dag</h2>${watch.length?watch.map(x=>cowCard(x.c,x.s)).join(''):`<div class="card empty">✅ Ingen kyr krev ekstra oppfølging akkurat no.</div>`}<h2>Alle kyr</h2><div class="legend"><span><i class="green"></i>normal</span><span><i class="yellow"></i>følg med</span><span><i class="orange"></i>truleg brunst</span><span><i class="red"></i>kontakt inseminør</span></div>${list.map(x=>cowCard(x.c,x.s)).join('')||`<div class="card empty">Ingen kyr registrerte.<br><button onclick="openCowForm()">Legg til første ku</button></div>`}`;
}
function todayKey(){return localDateTime().slice(0,10)}
function morningOverview(watch){const now=new Date(),current=now.toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'}),ready=current>=state.settings.morningTime,checked=state.morningChecks[todayKey()];const names=watch.map(x=>esc(cowName(x.c))).join(', ');return `<section class="card morning-card"><div class="row"><div><h2>🌅 Dagens kontroll</h2><p class="muted">Fast morgontid: ${state.settings.morningTime}${ready?' · Oversikta er klar':' · Førehandsvisning'}</p></div><span class="badge ${checked?'green':ready?'orange':'yellow'}">${checked?'Gjennomført':ready?'Klar no':'Før '+state.settings.morningTime}</span></div><p>${watch.length?`Du bør følgje med på <strong>${watch.length}</strong> ${watch.length===1?'ku':'kyr'}: ${names}.`:'✅ Ingen kyr krev ekstra oppfølging i morgonkontrollen.'}</p>${checked?`<div class="meta">Markert gjennomført ${fmt(checked)}</div>`:`<button onclick="markMorningCheck()">Marker morgonkontroll som gjennomført</button>`}</section>`}
function markMorningCheck(){state.morningChecks[todayKey()]=new Date().toISOString();save();renderToday();toast('Morgonkontrollen er markert som gjennomført')}
function cowCard(c,s){return `<article class="card cow-card" onclick="openCow('${c.id}')"><i class="status-dot ${s.level}"></i><div><h3>${esc(cowName(c))}</h3><div class="meta">${esc(s.label)} · Neste brunst: ${nextHeat(c)}</div>${inseminationEligibilityText(c)?`<div class="meta">${inseminationEligibilityText(c)}</div>`:''}${windowText(c)?`<div class="meta">${windowText(c)}</div>`:''}</div><span>›</span></article>`}
function renderCows(){
  $('#app').innerHTML=`<div class="row"><div><h1>Kyr</h1><p class="muted">${state.cows.length} registrerte dyr · sortert på individnummer</p></div><button onclick="openCowForm()">＋ Legg til ku</button></div><input id="cowSearch" placeholder="Søk på namn eller nummer" oninput="filterCows(this.value)"><div id="cowList">${[...state.cows].sort(compareCowNumber).map(c=>cowCard(c,status(c))).join('')||'<div class="empty">Ingen kyr registrerte</div>'}</div>`;
}
function filterCows(q){const s=q.toLowerCase();$('#cowList').innerHTML=state.cows.filter(c=>cowName(c).toLowerCase().includes(s)).sort(compareCowNumber).map(c=>cowCard(c,status(c))).join('')||'<div class="empty">Ingen treff</div>'}
function renderObserve(){
  if(!state.cows.length){$('#app').innerHTML='<h1>Registrer brunstteikn</h1><div class="card empty">Legg til ei ku først.<br><button onclick="openCowForm()">Legg til ku</button></div>';return}
  $('#app').innerHTML=`<h1>Registrer observasjon</h1><p class="muted">Tidspunktet blir fylt ut automatisk.</p><form id="obsForm" class="card"><label>Ku</label><select name="cowId" required><option value="">Vel ku</option>${state.cows.map(c=>`<option value="${c.id}">${esc(cowName(c))}</option>`).join('')}</select><label>Tidspunkt</label><input type="datetime-local" name="at" value="${localDateTime()}" required><label>Kva vil du registrere?</label><div class="sign-grid">${SIGNS.map(s=>`<label class="sign"><input type="checkbox" name="signs" value="${s[0]}"><span>${s[1]}</span></label>`).join('')}<label class="sign"><input id="inseminationCheck" type="checkbox" name="insemination" value="yes"><span>Inseminering</span></label></div><div id="semenFields" class="hidden"><label>Type inseminering</label><select name="semenType"><option value="">Vel type</option>${SEMEN_TYPES.map(t=>`<option value="${t}">${t}</option>`).join('')}</select></div><label>Notat (valfritt)</label><textarea name="note" placeholder="Til dømes aktivitetsmålar, styrke eller andre observasjonar"></textarea><button type="submit">Lagre registrering</button></form><div class="notice">Eitt teikn åleine er ikkje alltid sikker brunst. Ståbrunst er det sikraste teiknet. Insemineringstidspunkt avheng òg av sædtype – bruk appen som støtte og avtal med inseminør/veterinær.</div>`;
  $('#obsForm').onsubmit=saveObservation;
  $('#inseminationCheck').onchange=e=>{const fields=$('#semenFields'),select=fields.querySelector('select');fields.classList.toggle('hidden',!e.target.checked);select.required=e.target.checked};
}
function renderHistory(){
 const events=[...state.events].sort((a,b)=>new Date(b.at)-new Date(a.at));
 $('#app').innerHTML=`<h1>Historikk</h1><div class="tabs"><button class="active" onclick="historyFilter('all',this)">Alle</button><button onclick="historyFilter('observation',this)">Brunstteikn</button><button onclick="historyFilter('insemination',this)">Inseminering</button><button onclick="historyFilter('pregnant',this)">Drektigheit</button><button onclick="historyFilter('calving',this)">Kalving</button></div><div id="historyList">${historyHtml(events)}</div>`;
}
function historyHtml(events){return events.length?`<div class="card timeline">${events.map(e=>{const c=state.cows.find(c=>c.id===e.cowId);return `<div class="event"><strong>${esc(c?cowName(c):'Sletta ku')} · ${eventTitle(e)}</strong><div class="meta">${fmt(e.at)}</div>${e.note?`<div>${esc(e.note)}</div>`:''}</div>`}).join('')}</div>`:'<div class="card empty">Ingen hendingar registrerte</div>'}
function historyFilter(type,btn){document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$('#historyList').innerHTML=historyHtml(type==='all'?state.events:state.events.filter(e=>e.type===type))}
function eventTitle(e){if(e.type==='observation')return (e.signs||[]).map(k=>SIGNS.find(s=>s[0]===k)?.[1]).filter(Boolean).join(', ');if(e.type==='insemination')return `Inseminert${e.semenType?' · '+e.semenType:''}`;if(e.type==='pregnant')return `Drektig${e.expectedCalving?' · venta kalving '+fmtDate(e.expectedCalving):''}`;return {notPregnant:'Ikkje drektig',calving:'Kalving'}[e.type]||e.type}
function renderSettings(){
 $('#app').innerHTML=`<h1>Innstillingar</h1><form id="settingsForm" class="card"><label>Tidspunkt for morgonoversikt</label><input type="time" name="morningTime" value="${state.settings.morningTime}" required><label>Normal brunstsyklus (dagar)</label><input type="number" name="cycleDays" min="17" max="25" value="${state.settings.cycleDays}"><label>Standard drektigheitslengd (dagar)</label><input type="number" name="gestationDays" min="260" max="300" value="${state.settings.gestationDays}"><label>Start varsling før venta brunst (dagar)</label><input type="number" name="watchDays" min="1" max="7" value="${state.settings.watchDays}"><label><input style="width:auto" type="checkbox" name="notify" ${state.settings.notify?'checked':''}> Vis lokale varsel når appen blir opna</label><button type="submit">Lagre innstillingar</button></form><section class="card"><h2>Data og sikkerheitskopi</h2><p class="muted">Opplysningane er lagra berre på denne eininga. Ta sikkerheitskopi dersom data er viktige.</p><div class="actions"><button onclick="exportData()">Eksporter data</button><button class="secondary" onclick="$('#importFile').click()">Importer data</button><input id="importFile" class="hidden" type="file" accept="application/json" onchange="importData(this)"></div></section><section class="card"><h2>Om vurderingane</h2><p>Status byggjer på teikna du registrerer, ståbrunst og venta syklus. Venta kalvingsdato blir berekna frå siste inseminering med standard ${state.settings.gestationDays} dagar. Datoane er rettleiande og kan variere med individ og rase.</p></section>`;
 $('#settingsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.settings={morningTime:f.get('morningTime'),cycleDays:Number(f.get('cycleDays')),gestationDays:Number(f.get('gestationDays')),watchDays:Number(f.get('watchDays')),notify:f.get('notify')==='on'};save();renderSettings();toast('Innstillingane er lagra')};
}
function openCowForm(cowId){const c=state.cows.find(x=>x.id===cowId)||{};showModal(`<h2>${c.id?'Rediger ku':'Legg til ku'}</h2><form id="cowForm"><input type="hidden" name="id" value="${c.id||''}"><label>Individnummer *</label><input name="number" required value="${esc(c.number||'')}"><label>Namn</label><input name="name" value="${esc(c.name||'')}"><div class="row"><div><label>Fødselsdato</label><input type="date" name="birth" value="${c.birth||''}"></div><div><label>Siste kalving</label><input type="date" name="lastCalving" value="${c.lastCalving||''}"></div></div><button type="submit">Lagre ku</button></form>`);$('#cowForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));if(o.id){Object.assign(state.cows.find(x=>x.id===o.id),o)}else{state.cows.push({...o,id:uid()})}save();closeModal();route='cows';render();toast('Kua er lagra')};}
function openCow(id){const c=state.cows.find(c=>c.id===id);if(!c)return;const ev=eventsFor(id),calving=expectedCalving(c);showModal(`<h2>${esc(cowName(c))}</h2><p class="muted">${c.birth?'Fødd '+fmtDate(c.birth):'Fødselsdato ikkje registrert'}${c.lastCalving?' · Siste kalving '+fmtDate(c.lastCalving):''}</p><div class="card"><strong>Status: ${status(c).label}</strong><div class="meta">Venta neste brunst: ${nextHeat(c)}</div>${inseminationEligibilityText(c)?`<div class="meta"><strong>${inseminationEligibilityText(c)}</strong></div>`:''}${calving?`<div class="meta">Berekna kalving: ${fmtDate(calving)}</div>`:''}${windowText(c)?`<div>${windowText(c)}</div>`:''}</div><div class="actions"><button onclick="openInsemination('${id}')">Inseminert</button><button onclick="quickEvent('${id}','pregnant')">Drektig</button><button onclick="quickEvent('${id}','notPregnant')">Ikkje drektig</button><button onclick="quickEvent('${id}','calving')">Kalva</button></div><h3>Historikk</h3>${historyHtml(ev)}<div class="actions"><button class="secondary" onclick="closeModal();openCowForm('${id}')">Rediger ku</button><button class="danger" onclick="deleteCow('${id}')">Slett ku</button></div>`)}
function openInsemination(id){const c=state.cows.find(c=>c.id===id),eligibility=inseminationEligibilityText(c);showModal(`<h2>Registrer inseminering</h2>${eligibility?`<div class="notice">⚠️ ${eligibility}</div>`:''}<form id="inseminationForm"><label>Tidspunkt</label><input type="datetime-local" name="at" value="${localDateTime()}" required><label>Type inseminering</label><select name="semenType" required><option value="">Vel type</option>${SEMEN_TYPES.map(t=>`<option value="${t}">${t}</option>`).join('')}</select><label>Notat (valfritt)</label><textarea name="note"></textarea><button type="submit">Lagre inseminering</button></form>`);$('#inseminationForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.events.push({id:uid(),cowId:id,type:'insemination',at:new Date(f.get('at')).toISOString(),semenType:f.get('semenType'),note:f.get('note')});save();openCow(id);toast('Insemineringa er lagra')}}
function quickEvent(id,type){const event={id:uid(),cowId:id,type,at:new Date().toISOString(),note:''};if(type==='pregnant'){const insemination=eventsFor(id,'insemination')[0];if(insemination){const due=new Date(insemination.at);due.setDate(due.getDate()+Number(state.settings.gestationDays));event.expectedCalving=due.toISOString();event.inseminationId=insemination.id}}state.events.push(event);if(type==='calving')state.cows.find(c=>c.id===id).lastCalving=new Date().toISOString().slice(0,10);save();openCow(id);toast(type==='pregnant'&&event.expectedCalving?`Drektig registrert · venta kalving ${fmtDate(event.expectedCalving)}`:'Hendinga er lagra')}
function deleteCow(id){if(!confirm('Slette kua og heile historikken hennar?'))return;state.cows=state.cows.filter(c=>c.id!==id);state.events=state.events.filter(e=>e.cowId!==id);save();closeModal();render();toast('Kua er sletta')}
function saveObservation(e){e.preventDefault();const f=new FormData(e.target),signs=f.getAll('signs'),insemination=f.get('insemination')==='yes';if(!signs.length&&!insemination){toast('Vel minst éi registrering');return}const at=new Date(f.get('at')).toISOString(),note=f.get('note');if(signs.length)state.events.push({id:uid(),cowId:f.get('cowId'),type:'observation',at,signs,note});if(insemination)state.events.push({id:uid(),cowId:f.get('cowId'),type:'insemination',at,semenType:f.get('semenType'),note});save();route='today';render();toast(insemination?'Registreringa og insemineringa er lagra':'Observasjonen er lagra');checkNotifications()}
function showModal(html){$('#modalBody').innerHTML=html;$('#modal').showModal()}function closeModal(){$('#modal').close()}
function localDateTime(){const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,16)}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`brunstreg-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(input){const file=input.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!Array.isArray(data.cows)||!Array.isArray(data.events))throw 0;state={...data,morningChecks:data.morningChecks||{},settings:{...defaultSettings,...data.settings}};save();render();toast('Data er importerte')}catch{alert('Fila kunne ikkje lesast som Brunstreg-data')}};r.readAsText(file)}
async function checkNotifications(){if(!state.settings.notify||!('Notification'in window))return;if(Notification.permission==='default')await Notification.requestPermission();if(Notification.permission!=='granted')return;const urgent=state.cows.filter(c=>status(c).priority>=3);if(urgent.length)new Notification('Brunstreg',{body:`${urgent.length} ${urgent.length===1?'ku bør':'kyr bør'} følgjast opp no.`,icon:'icon.svg'})}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{route=b.dataset.route;render()});$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{await installPrompt?.prompt();installPrompt=null;$('#installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();setTimeout(checkNotifications,1000);
